### ISSUE TITLE
Can it work on MacOS?

### ISSUE THREAD

**Issue by binhdao112** [shamanec/GADS-devices-provider#13]
I'm trying to start GADS in macOS. Can it run on MacOS?

Thanks for reading my issue

**Comment by shamanec** [comment]
You can run `GADS` in macOS but you cannot run `GADS-devices-provider` in macOS. This part of the project uses `udev` subsystem on Linux to symlink the devices to `/dev`, which in turn is being listened to by the provider to automatically create/destroy containers. If some day I have access to a Mac I might try and get it working using a different approach, but for the moment it works only on Linux :)

**Comment by binhdao112** [comment]
How to run it on macos =(( 

Can you help me ^^ Thanks you so much

**Comment by shamanec** [comment]
Sorry but you cannot run it on macOS, you need a Linux machine :)

**Comment by binhdao112** [comment]
no i want to ask about "How to run GADS on mac as you said" because it have not README to setup :(

**Comment by shamanec** [comment]
There are READMEs [here](https://github.com/shamanec/GADS-devices-provider/blob/main/docs/setup.md) and [here](https://github.com/shamanec/GADS/blob/main/README.md). `GADS` UI can be compiled on macOS and you can run it, but this is it. To provide devices to `GADS` you need to run `GADS-devices-provider` on a Linux machine. As I've already stated - project is not intended to work on macOS, you need a Linux machine

**Comment by binhdao112** [comment]
oke Thanks sir 

I hope one day you can run it on macos :(

**Comment by shamanec** [comment]
@binhdao112 It does run on macOS now, you can check it out if you are still interested :)

**Comment by binhdao112** [comment]
> @binhdao112 It does run on macOS now, you can check it out if you are still interested :)

@shamanec OMG, I'm so happy while hear this, I will retry it and feedback for you soon

Thanks sir ^^

**Comment by shamanec** [comment]
If you encounter any problems raise issues or contact me on Discord(can be found in my profile) :P
