### ISSUE TITLE
Unable to start the GADS Server. Logs don't show anything

### ISSUE THREAD

**Issue by mayukhsinha** [shamanec/GADS-devices-provider#34]
Hi,
I have completed the setup and I am not able to keep the server running. It starts for a few seconds and then terminates itself.
Logs don't show any errors. Here are the logs:

`
➜  GADS-devices-provider git:(main) ✗ go build .
➜  GADS-devices-provider git:(main) ✗ ./GADS-devices-provider 
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /device/:udid/health      --> github.com/shamanec/GADS-devices-provider/router.DeviceHealth (3 handlers)
[GIN-debug] POST   /device/:udid/tap         --> github.com/shamanec/GADS-devices-provider/router.DeviceTap (3 handlers)
[GIN-debug] POST   /device/:udid/home        --> github.com/shamanec/GADS-devices-provider/router.DeviceHome (3 handlers)
[GIN-debug] POST   /device/:udid/lock        --> github.com/shamanec/GADS-devices-provider/router.DeviceLock (3 handlers)
[GIN-debug] POST   /device/:udid/unlock      --> github.com/shamanec/GADS-devices-provider/router.DeviceUnlock (3 handlers)
[GIN-debug] POST   /device/:udid/screenshot  --> github.com/shamanec/GADS-devices-provider/router.DeviceScreenshot (3 handlers)
[GIN-debug] POST   /device/:udid/swipe       --> github.com/shamanec/GADS-devices-provider/router.DeviceSwipe (3 handlers)
[GIN-debug] GET    /device/:udid/appiumSource --> github.com/shamanec/GADS-devices-provider/router.DeviceAppiumSource (3 handlers)
[GIN-debug] POST   /device/:udid/typeText    --> github.com/shamanec/GADS-devices-provider/router.DeviceTypeText (3 handlers)
[GIN-debug] POST   /device/:udid/clearText   --> github.com/shamanec/GADS-devices-provider/router.DeviceClearText (3 handlers)
[GIN-debug] GET    /device/:udid/appium/*proxyPath --> github.com/shamanec/GADS-devices-provider/router.AppiumReverseProxy (3 handlers)
[GIN-debug] POST   /device/:udid/appium/*proxyPath --> github.com/shamanec/GADS-devices-provider/router.AppiumReverseProxy (3 handlers)
[GIN-debug] PUT    /device/:udid/appium/*proxyPath --> github.com/shamanec/GADS-devices-provider/router.AppiumReverseProxy (3 handlers)
[GIN-debug] PATCH  /device/:udid/appium/*proxyPath --> github.com/shamanec/GADS-devices-provider/router.AppiumReverseProxy (3 handlers)
[GIN-debug] HEAD   /device/:udid/appium/*proxyPath --> github.com/shamanec/GADS-devices-provider/router.AppiumReverseProxy (3 handlers)
[GIN-debug] OPTIONS /device/:udid/appium/*proxyPath --> github.com/shamanec/GADS-devices-provider/router.AppiumReverseProxy (3 handlers)
[GIN-debug] DELETE /device/:udid/appium/*proxyPath --> github.com/shamanec/GADS-devices-provider/router.AppiumReverseProxy (3 handlers)
[GIN-debug] CONNECT /device/:udid/appium/*proxyPath --> github.com/shamanec/GADS-devices-provider/router.AppiumReverseProxy (3 handlers)
[GIN-debug] TRACE  /device/:udid/appium/*proxyPath --> github.com/shamanec/GADS-devices-provider/router.AppiumReverseProxy (3 handlers)
[GIN-debug] GET    /device/:udid/android-stream --> github.com/shamanec/GADS-devices-provider/router.AndroidStreamProxy (3 handlers)
[GIN-debug] GET    /device/:udid/ios-stream  --> github.com/shamanec/GADS-devices-provider/router.IosStreamProxy (3 handlers)
[GIN-debug] [WARNING] You trusted all proxies, this is NOT safe. We recommend you to set a value.
Please check https://pkg.go.dev/github.com/gin-gonic/gin#readme-don-t-trust-all-proxies for details.
[GIN-debug] Listening and serving HTTP on :10001
➜  GADS-devices-provider git:(main) ✗ 

`

What could be the possible reasons for this?

**Comment by shamanec** [comment]
All logs are recorded both in a Mongo collection and also in a local file in the provider folder `./logs/provider.log` - you should check out there and let me know the error :) You could also contact me on Discord for faster communication, it can be found in my profile on Github :)

**Comment by shamanec** [comment]
Closed due to inactivity
