### ISSUE TITLE
Unable to start device provider server.

### ISSUE THREAD

**Issue by Code-P6** [shamanec/GADS-devices-provider#36]
I am planning to implement iOS device farm. Setup the GADS UI while trying to start the device provider server, getting below error,

<img width="568" alt="image" src="https://github.com/shamanec/GADS-devices-provider/assets/28931942/0ff19039-2d9b-4248-ab0c-e257554ec67c">

I am using macOS and followed the instructions in doc for setting up. I am planning to test 1 android and 1 iOS device.

**Comment by shamanec** [comment]
Yeah, my bad for this, I need to add a check for that folder and create it programatically. Just do `mkdir logs` in the provider repo or just create the `logs` folder manually and re-run the provider. You might encounter other issues like this - contact me on [Discord ](https://discordapp.com/users/365565274470088704) for faster communication if you want :)

**Comment by shamanec** [comment]
Also you are not going to get a lot of output in the Terminal, for logs/errors you should look inside the `provider.log` file after the provider starts

**Comment by Code-P6** [comment]
@shamanec Thanks for the quick response mate. It worked like a charm.. Would love to collaborate with you for enhancing this framework. Will reach out to you in discord sooner.

**Comment by Code-P6** [comment]
Hi @shamanec Your discord link got expired. Can you share a new one

**Comment by shamanec** [comment]
@Code-P6 I wonder why, when I click it, it points to my profile 😓 You can try and find me by `365565274470088704` userID or `shamanec` :)
